### ISSUE TITLE
Detailed install 

### ISSUE THREAD

**Issue by lexcorp** [flexnst/laravel-lgtv#2]
Hi, I’m trying to install laravel-lgtv but I can’t get success.

What versión of php is required?
What version of laravel is required?

Please can you more details of install process…

thanks…

**Comment by lexcorp** [comment]
These are my steps to install

1.-
composer create-project --prefer-dist laravel/laravel laravel-lgtv


2.-
composer require flexnst/laravel-lgtv

3.-
cd laravel-lgtv/

4.-
php artisan vendor:publish --provider="Flexnst\LgTv\LgTvServiceProvider" --tag=config

5.-
php artisan serve

6.-
http://127.0.0.1:8000/

**Comment by flexnst** [comment]
Hi lexcorp, this is not an application, but a package that provides out-of-the-box functions specified in the Readme.md that you can use in your application. The package does not have a UI, you must implement it yourself in your laravel based application.
Required laravel version, you can see in composer.json file.
